### ISSUE TITLE
Exact Match

### ISSUE THREAD

**Issue by nglasl** [nyeholt/silverstripe-extensible-elastic#5]
It's currently not possible to search using a phrase wrapped in quotation marks for exact match, however this **is** something that's supported when doing a raw query. It seems like the solution is to build the query correctly based on the user input (when quotation marks have been used).

**Comment by nyeholt** [comment]
Are you meaning that you receive results that have the phrase pieces without being exactly matched? There was a recent update that introduced phase_prefix matching that may need to detect presence of double quotes before doing the phrase prefixing

**Comment by nglasl** [comment]
From what I remember, doing an exact match search was just straight up not giving results when it should have been (and did so when doing a raw query outside this module).

**Comment by nglasl** [comment]
I'm going to close this issue for now, as I was hoping it may get a little more traction from the community. If it's something that I encounter again and need to solve, I'll investigate and submit a PR. At the moment it's hard for me to say whether this remains an issue.
